### ISSUE TITLE
Error in the McMMOPlayerXpGainEvent and a null error i do the cmd of /StatsGui show.

### ISSUE THREAD

**Issue by XxCoolGamesxX** [Cybermaxke/StatsGui#2]
2013-03-21 23:50:30 [SEVERE] Could not pass event McMMOPlayerXpGainEvent to mcMMOStats v1.4
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:39)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:466)
    at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:442)
    at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:430)
    at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:42)
    at com.gmail.nossr50.skills.acrobatics.AcrobaticsManager.dodgeCheck(AcrobaticsManager.java:60)
    at com.gmail.nossr50.util.skills.CombatUtils.combatChecks(CombatUtils.java:272)
    at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:129)
    at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:613)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:39)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
    at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:84)
    at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:372)
    at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:394)
    at net.minecraft.server.v1_5_R2.EntityLiving.damageEntity(EntityLiving.java:698)
    at net.minecraft.server.v1_5_R2.EntityHuman.damageEntity(EntityHuman.java:685)
    at net.minecraft.server.v1_5_R2.EntityPlayer.damageEntity(EntityPlayer.java:352)
    at net.minecraft.server.v1_5_R2.EntityMonster.m(EntityMonster.java:88)
    at net.minecraft.server.v1_5_R2.EntityMonster.a(EntityMonster.java:114)
    at net.minecraft.server.v1_5_R2.EntitySpider.a(EntitySpider.java:91)
    at net.minecraft.server.v1_5_R2.EntityCreature.bq(EntityCreature.java:56)
    at net.minecraft.server.v1_5_R2.EntityLiving.c(EntityLiving.java:1319)
    at net.minecraft.server.v1_5_R2.EntityMonster.c(EntityMonster.java:20)
    at net.minecraft.server.v1_5_R2.EntityLiving.l_(EntityLiving.java:544)
    at net.minecraft.server.v1_5_R2.EntityMonster.l_(EntityMonster.java:24)
    at net.minecraft.server.v1_5_R2.EntitySpider.l_(EntitySpider.java:20)
    at net.minecraft.server.v1_5_R2.World.entityJoinedWorld(World.java:1455)
    at net.minecraft.server.v1_5_R2.WorldServer.entityJoinedWorld(WorldServer.java:629)
    at net.minecraft.server.v1_5_R2.World.playerJoinedWorld(World.java:1431)
    at net.minecraft.server.v1_5_R2.World.tickEntities(World.java:1303)
    at net.minecraft.server.v1_5_R2.WorldServer.tickEntities(WorldServer.java:495)
    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:561)
    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:229)
    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:471)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:403)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
    at me.cybermaxke.mcmmostats.McMMOStats.onMcMMOPlayerXpGain(McMMOStats.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:613)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 44 more

and 

2013-03-21 23:50:01 [INFO] XxCoolGamesxX issued server command: /StatsGui show
2013-03-21 23:50:01 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'statsgui' in plugin mcMMOStats v1.4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:187)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchCommand(CraftServer.java:545)
    at net.minecraft.server.v1_5_R2.PlayerConnection.handleCommand(PlayerConnection.java:980)
    at net.minecraft.server.v1_5_R2.PlayerConnection.chat(PlayerConnection.java:896)
    at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:840)
    at net.minecraft.server.v1_5_R2.Packet3Chat.handle(Packet3Chat.java:44)
    at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:174)
    at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:113)
    at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
    at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:66)
    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:582)
    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:229)
    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:471)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:403)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
    at me.cybermaxke.mcmmostats.GuiCommand.onCommand(GuiCommand.java:59)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

I use the Spigot - 692.
I use the mcmmo - 1.4.04 - 1824.
I use the mcMMOStatsGui - 1.4.

**Comment by deerfoxcritter** [comment]
Found Exact Bug on my server too
http://pastie.org/7030967
http://pastie.org/7030872

**Comment by XxCoolGamesxX** [comment]
@908070p The first error you report. You use old 1.3 update to 1.4 of the plugin and the second error you report some at my of the error of null. : D

**Comment by zrocweb** [comment]
Download the latest build of the plugin, as well as mcMMO and bukkit, at least build 2691 (1.5.1)

**Comment by XxCoolGamesxX** [comment]
Yup is fix now. Thx for your help.

**Comment by zrocweb** [comment]
cool. good to hear!!
